FROM node:14.17.6

RUN apt update \
    && apt install -y git

WORKDIR /usr/src/app/my-app

RUN git config --global user.email "nkusumichee1367@gmail.com" \
    && git config --global user.name "Michée NKUSU"

